import { Inter } from "next/font/google";
import "./globals.css";
import {Quicksand} from "next/font/google";

const FontPrincipal = Quicksand ({ subsets: ["latin"], weight: ['400'] });

export const metadata = {
  title: "Catpédia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={FontPrincipal.className}>{children}</body>
    </html>
  );
}
